
import Navbar from "@/components/Navbar";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function () {
  return (
    <html lang="en">
      <body>
        <Navbar/>
       
      </body>
    </html>
  );
}
