

import Hero from "@/components/Hero";
import ThemeToggle from "@/components/ThemeToggle";

import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function () {
  return (
    <html lang="en">
      <body>
         
        <Hero />
        <ThemeToggle attribute="class"
          enableSystem={true}
          defaultTheme="system"/>
       
      </body>
    </html>
  );
}
